name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'

    - name: Install dependencies
      run: yarn install

    - name: Build application
      run: yarn run build  

    - name: Deploy to Hostinger
      env:
        KEY_BOOK_CLUB: ${{ secrets.KEY_BOOK_CLUB }}
      run: |
        mkdir -p ~/.ssh/
        echo "$KEY_BOOK_CLUB" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 212.107.17.238 >> ~/.ssh/known_hosts
        # Debugging steps to check the SSH setup
        echo "SSH directory contents:"
        ls -la ~/.ssh/
        echo "Attempting SSH connection:"
        ssh -v -o StrictHostKeyChecking=no u208111771@212.107.17.238 'echo "SSH connection successful"; git pull origin main && yarn install && yarn run build'